[project]
name = "group2-randomizer"
version = "0.1.0"
description = "Cohort Room Randomizer"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "rich>=14.3.3",
]

[tool.pyright]
ignore = ["*"]
